In [109]:
import importlib
import foresight.model
import foresight.data_functions as fx_df
importlib.reload(foresight.model)
importlib.reload(fx_df)
import numpy as np

import sklearn.preprocessing as skpp

In [84]:
data = np.random.random(200)#[0]
d2 = np.random.random(500)#[0]
#print(data)

in_, out_ = fx_df.series_to_supervised(data, n_in=4, n_out=1)

#print(in_)
#print("\n")
#print(out_)

idx = 2

out_[idx] = np.array([25])
#print("\n")
#print(out_)

In [85]:
#scaler_ = skpp.MinMaxScaler((-1, 1))

txr = fx_df.Data_Transformer(transform = 'LogDiff', remove_outliers = True)

#    def __init__(    self, 
#                     transform=None,
#                     remove_outliers=False,
#                     scaler='MinMaxScaler')
#def data_transformer(data,
#                     transform=None,
#                     remove_outliers=False,
#                     scaler='MinMaxScaler'):


In [86]:
d1, scaler_ = txr(data)

In [44]:
txr2 = fx_df.Data_Transformer(transform = 'LogDiff', remove_outliers = True, scaler = scaler_)
d2a,_ = txr2(d2)

In [45]:
print(d2[:10])
print('\n')
print(d2a[:10])

[0.50581367 0.48464359 0.09488445 0.36113847 0.58265267 0.24960819
 0.46478924 0.29168865 0.14370979 0.90173351]


[[-0.02853641]
 [ 1.07997854]
 [ 1.07997854]
 [ 0.39023129]
 [-0.6754271 ]
 [ 0.50544354]
 [-0.36859343]
 [-0.56307109]
 [-0.04754586]
 [-0.04754586]]


In [57]:
dd1i, dd1o = fx_df.series_to_supervised(data = d1,
                         n_in=20,
                         n_out=1,
                         dropnan=True,
                         separate_output_series=True)

dd2i, dd2o = fx_df.series_to_supervised(data = d2,
                         n_in=20,
                         n_out=1,
                         dropnan=True,
                         separate_output_series=True)

dd1i = dd1i.reshape(
            (dd1i.shape[0], 20, 1))
dd1o = dd1o.reshape((-1, 1))
__oldest_datum = 0

In [75]:
dd2i = dd2i.reshape(
            (dd2i.shape[0], 20, 1))[:20]
dd2o = dd2o.reshape((-1, 1))

num_samples = dd1i.shape[0]
new_samples = dd2i.shape[0]

#print (dd1i)

print(num_samples)
print(new_samples)


if new_samples > num_samples:
    dd3i = dd2i[-num_samples:]
else:
    indices = np.arange(__oldest_datum, new_samples + __oldest_datum) % num_samples
    for i_src, i_tgt in enumerate(indices):
        dd3i[i_tgt] = dd2i[i_src]
    __oldest_datum += new_samples
    print (indices)

#print(dd3i)

179
20
[161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
   0   1]


In [77]:
cur = 0
tot = 1490
rf = 355

idx = range(0, tot, rf)
for n in idx:
    print(n, n+rf -1 if n + rf -1 <= tot else tot)

0 354
355 709
710 1064
1065 1419
1420 1490


In [131]:
my_data = np.arange(1,100)
txr1 = fx_df.Data_Transformer(transform = 'LogDiff', remove_outliers = True)
d1, scaler_ = txr1(my_data)
in_, out_ = fx_df.series_to_supervised(d1, n_in=60, n_out=1)

print(my_data)
#print(out_)
print (len(out_))
#print(out_[0])
#print(out_[0].reshape(-1,1))
print(my_data[61])
o1 = txr1.Invert(out_)
o2 = np.exp(o1)
#print(o1)
#print(o2)

x00 = np.array(range(61,100))
x01 = np.log(x00)
x02 = x01[1:] - x01[:-1]
print(x02[:10])
#print(x00, x01, x01[1:] - x01[:-1])

x03 = x02 + x01[:-1]
print(np.exp(x03[:10]))

x0 = txr1.Invert(out_)
x1 = np.exp(x0)

print (61 * x1[0])
print (x0, x1)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
38
62
[0.01626052 0.01600034 0.01574836 0.01550419 0.01526747 0.01503788
 0.01481509 0.0145988  0.01438874 0.01418463]
[62. 63. 64. 65. 66. 67. 68. 69. 70. 71.]
[62.]
[[0.01626052]
 [0.01600034]
 [0.01574836]
 [0.01550419]
 [0.01526747]
 [0.01503788]
 [0.01481509]
 [0.0145988 ]
 [0.01438874]
 [0.01418463]
 [0.01398624]
 [0.01379332]
 [0.01360565]
 [0.01342302]
 [0.01324523]
 [0.01307208]
 [0.0129034 ]
 [0.01273903]
 [0.01257878]
 [0.01242252]
 [0.01227009]
 [0.01212136]
 [0.01197619]
 [0.01183446]
 [0.01169604]
 [0.01156082]
 [0.0114287 ]
 [0.01129956]
 [0.0111733 ]
 [0.01104984]
 [0.01092907]
 [0.01081092]
 [0.01069529]
 [0.01058211]
 [0.0104713 ]
 [0.01036279]
 [0.0102565 ]
 [0.01015237

In [132]:
start_idx = 0
retrain_freq = 2000
total_data = out_.shape[0]

last_idx = start_idx + retrain_freq -1 if start_idx + self.retrain_freq -1 <= total_data else total_data
y_hat = self._model.Forecast(_ins[start_idx:last_idx])
y_hat_unscaled = txn.inverse_transform(y_hat)
bid_hat = np.exp(y_hat) * self._data.iloc[start_idx + idx_offset - 1 : last_idx + idx_offset - 1]

NameError: name 'self' is not defined

In [ ]:
Reinforcement of hummingbird squash is in fox light
